# Generated by Django 4.2.1 on 2023-05-26 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Премьера в мире'),
        ),
    ]
